In [1]:
4 + "5"

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [2]:
5 / 0

ZeroDivisionError: division by zero

In [3]:
int("5")

5

In [4]:
int("a")

ValueError: invalid literal for int() with base 10: 'a'

In [5]:
l = [1, 2, 3]

In [6]:
l[2]

3

In [17]:
d = {"k": [4, 5, 7], "v": "hola"}

In [18]:
d["k"]

[4, 5, 7]

In [19]:
d["v"]

'hola'

In [11]:
d = {"k": 3, 4: 5}

In [12]:
d[4]

5

In [15]:
a = {"l": 6, "o": 3}

In [16]:
{**d, **a}

{'k': 3, 4: 5, 'l': 6, 'o': 3}

In [20]:
d

{'k': [4, 5, 7], 'v': 'hola'}

In [21]:
d['v'] = 4

In [22]:
d

{'k': [4, 5, 7], 'v': 4}

In [24]:
d["l"] = 8

In [25]:
d

{'k': [4, 5, 7], 'v': 4, 'l': 8}

In [27]:
if "a" in d:
    print(d["a"])

In [28]:
d.items()

dict_items([('k', [4, 5, 7]), ('v', 4), ('l', 8)])

In [29]:
d.keys()

dict_keys(['k', 'v', 'l'])

In [30]:
d.values()

dict_values([[4, 5, 7], 4, 8])

In [31]:
len(d)

3

In [32]:
import numpy as np

In [38]:
l1 = np.array([1, 2, 3])
l2 = np.array([4, 5])

In [39]:
l1 + l2

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [37]:
l1 + 1

array([2, 3, 4])

In [40]:
l1.shape

(3,)

In [41]:
l2.shape

(2,)

In [42]:
np.sin(l1)

array([0.84147098, 0.90929743, 0.14112001])

In [43]:
np.mean(l1)

2.0

In [44]:
x = np.arange(10)

In [45]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
x[2]

2

In [59]:
data = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16], [1, 2, 3, 4]])

In [49]:
data

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [50]:
data[2, 2]

11

In [51]:
data[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [52]:
data[1:3, 3]

array([ 8, 12])

In [53]:
data[3, 0:3]

array([13, 14, 15])

In [54]:
data[3, :4]

array([13, 14, 15, 16])

In [60]:
data

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 1,  2,  3,  4]])

In [61]:
data.mean()

7.3

In [62]:
np.mean(data, axis=0)

array([5.8, 6.8, 7.8, 8.8])

In [63]:
np.mean(data, axis=1)

array([ 2.5,  6.5, 10.5, 14.5,  2.5])

In [67]:
a = np.arange(0, 20)

In [68]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [69]:
a.reshape((4, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [70]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [71]:
b = np.arange(50, 60)

In [72]:
np.concatenate((a, b))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [73]:
b = a.reshape((4, 5))

In [74]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [77]:
a = np.array([[5, 6, 7, 8, 9]])

In [83]:
c = np.concatenate((a, b), axis=0)

In [79]:
a.shape

(1, 5)

In [80]:
b.shape

(4, 5)

In [81]:
a

array([[5, 6, 7, 8, 9]])

In [82]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [84]:
c

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [85]:
np.concatenate((c, c), axis=0)

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [86]:
np.concatenate((c, c), axis=1)

array([[ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 15, 16, 17, 18, 19]])

In [1]:
import pandas as pd
import numpy as np
pd.DataFrame(np.random.randn(6,4))

0         1         2         3
0 -0.068083  0.318762  0.209628  0.694079
1 -1.111179 -1.943159 -0.806661 -1.049665
2 -0.731054 -0.986103  0.114975  0.591466
3 -0.280891 -0.773403 -0.454082  0.189530
4 -0.050997  1.135722  0.632349  2.330299
5  0.334660 -0.321694  0.528090  1.062369